# Site settings
baseURL = "https://blissful-golick-fb1bb0.netlify.com/"
languageCode = "en-US"
title = "Danny J. Liu | Agile Leader"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2019"

[params]

  # Metadata for search engines and social sharing
  author = "Danny J. Liu"
  description = "Danny Liu is an Agile Leader & Online Course Instructor."
  shareImage = "images/social.jpg"
  twitterHandle = "dannyjliu"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "#"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:dannyjliu@gmail.com"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/dannyjliu/"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/dannyjliu"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "My Work"

      [[params.links.list3.link]]
        text = "GitHub"
        url = "https://github.com/dannyjliu"

      [[params.links.list3.link]]
        text = "Link Two"
        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
